language: go
go:
    - 1.5
addons:
    postgresql: "9.4"
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mig"
    email:
        recipients:
            - ulfr@mozilla.com
        on_success: never
        on_failure: always
script:
    - export OLDPATH=$(pwd)
    - cd
    - mkdir -p "$GOPATH/src/mig.ninja/"
    - mv "$OLDPATH" "$GOPATH/src/mig.ninja/"
    - cd "$GOPATH/src/mig.ninja/mig"
    - make
    - yes | bash tools/standalone_install.sh
