language: go
go:
    - tip
addons:
    postgresql: "9.3"
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mig"
    email:
        recipients:
            - ulfr@mozilla.com
        on_success: never
        on_failure: always
script:
    - yes | bash tools/standalone_install.sh
