language: go
go:
    - 1.8
addons:
    postgresql: "9.4"
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mig"
services:
    - docker
before_install:
    # this is a fix to get rng-tools to work in travis-ci
    - sudo apt-get update -qq
    - sudo apt-get install --yes rng-tools
    - sudo rm -f /dev/random
    - sudo mknod -m 0666 /dev/random c 1 9
    - echo HRNGDEVICE=/dev/urandom | sudo tee /etc/default/rng-tools
    - sudo /etc/init.d/rng-tools restart
script:
    - export OLDPATH=$(pwd)
    - cd
    - mkdir -p "$GOPATH/src/mig.ninja/"
    - mv "$OLDPATH" "$GOPATH/src/mig.ninja/"
    - cd "$GOPATH/src/mig.ninja/mig"
    - diff mig-agent/configuration.go conf/mig-agent-conf.go.inc
    - diff mig-agent/available_modules.go conf/available_modules.go
    - diff mig-loader/configuration.go conf/mig-loader-conf.go.inc
    - diff client/mig-console/available_modules.go conf/available_modules.go
    - diff client/mig/available_modules.go conf/available_modules.go
    - sed -i 's,//_,_,' conf/available_modules.go
    - make
    - docker build -t mozilla/mig .
    - ./bin/linux/amd64/mig-agent-latest -i actions/example_v2.json
    - ./bin/linux/amd64/mig scribe -t all -z -path actions/scribe/usn-2015.json -onlytrue -human
    # If a TRAVIS_TAG is set, this build follows a git tag --push and should trigger
    # a release of a tagged container to dockerhub. Otherwise, we tag as latest.
    - |
        docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        if [ ! -z "$TRAVIS_TAG" ]; then
            docker tag app:build mozilla/mig:${TRAVIS_TAG}
            docker push mozilla/mig:${TRAVIS_TAG}
        else
            docker tag app:build mozilla/mig:latest
            docker push mozilla/mig:latest
        fi
        docker logout
