language: go
go:
    - tip
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mig"
before_install:
    - sudo apt-get install libreadline-dev
install:
    - make go_get_deps
script:
    - make mig-scheduler
    - make mig-api
    - make mig-cmd
    - make mig-console
    - make test AGTCONF=conf/mig-agent-conf.go.inc
